name: ethui-demo

services:
  - name: anvil
    github:
      repo: "ethui/demo"
      branch: "main"
      deploy_on_push: true
    dockerfile_path: ./.do/Dockerfile.anvil
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8545
    health_check: null
    envs:
      - key: "ANVIL_CHAIN_ID"
        value: "31338"

domains:
  - domain: anvil.demo.ethui.dev
    type: PRIMARY
