name: ethui-demo
services:
  - name: anvil
    github:
      repo: "ethui/demo"
      branch: "main"
      deploy_on_push: true
    dockerfile_path: ./.do/Dockerfile.anvil
    instance_count: 1
    instance_size_slug: basic-xxs

