name: nodejs

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yarn cache
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - run: yarn install
      - run: yarn lint
